# Generated by Django 2.0 on 2018-01-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customeranalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customeranalytics.Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customeranalytics.Company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customeranalytics.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Occassion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customeranalytics.Occassion'),
        ),
    ]
