# Generated by Django 2.0 on 2018-01-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Quandl', 'Quandl'), ('Reuters', 'Reuters'), ('IndexMundi', 'IndexMundi')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sunflower Oil', 'Sunflower Oil'), ('Palm Oil', 'Palm Oil'), ('Olive Oil', 'Olive Oil')], max_length=25)),
                ('summary', models.TextField(max_length=1000)),
                ('api_key', models.CharField(max_length=25)),
                ('api_version', models.CharField(blank=True, max_length=25)),
                ('api_code', models.CharField(max_length=20)),
                ('api_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommodityTracker.APISource')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommodityTracker.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommodityTracker.Commodity')),
            ],
        ),
    ]
