# Generated by Django 2.0 on 2018-01-05 18:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('api_source', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=25)),
                ('api_version', models.CharField(blank=True, max_length=25)),
                ('api_code', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(default=datetime.date(2000, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('company_name', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('weight1', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight2', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight3', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('benchmark1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_1', to='CommodityTracker.BaseCommodity')),
                ('benchmark2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_2', to='CommodityTracker.BaseCommodity')),
                ('benchmark3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_3', to='CommodityTracker.BaseCommodity')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_commodity', models.BooleanField(default=False)),
                ('is_purchase_commodity', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('base_commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='CommodityTracker.BaseCommodity')),
                ('purchase_commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='CommodityTracker.PurchaseCommodity')),
            ],
        ),
        migrations.AddField(
            model_name='basecommodity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basecommodities', to='CommodityTracker.Category'),
        ),
    ]
