# Generated by Django 2.0 on 2018-01-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='base_commodity',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='purchase_commodity',
        ),
        migrations.CreateModel(
            name='BaseCommodityRecords',
            fields=[
                ('commodityrecords_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CommodityTracker.CommodityRecords')),
                ('base_commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='CommodityTracker.BaseCommodity')),
            ],
            bases=('CommodityTracker.commodityrecords',),
        ),
        migrations.CreateModel(
            name='PurchaseCommodityRecords',
            fields=[
                ('commodityrecords_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CommodityTracker.CommodityRecords')),
                ('purchase_commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='CommodityTracker.PurchaseCommodity')),
            ],
            bases=('CommodityTracker.commodityrecords',),
        ),
        migrations.DeleteModel(
            name='TimeSeries',
        ),
    ]
